insert into tb_todo( titulo, descricao, data_para_finalizar, finalizado) values ('Estudar', 'Spring Boot com Angular', now(),false)
insert into tb_todo( titulo, descricao, data_para_finalizar, finalizado) values ('Estudar2', 'Spring Boot com Angular', now(),false)
insert into tb_todo( titulo, descricao, data_para_finalizar, finalizado) values ('Estudar3', 'Spring Boot com Angular', now(),false)
insert into tb_todo( titulo, descricao, data_para_finalizar, finalizado) values ('Estudar4', 'Spring Boot com Angular', now(),false)
insert into tb_todo( titulo, descricao, data_para_finalizar, finalizado) values ('Estudar5', 'Spring Boot com Angular', now(),true)
insert into tb_todo( titulo, descricao, data_para_finalizar, finalizado) values ('Estudar6', 'Spring Boot com Angular', now(),false)